version: "3.8"

services: 
  mongodb:
    image: mongo:latest
    container_name: 'user-service-mongodb'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root

    ports: 
      - 27017-27019:27017-27019